### ISSUE TITLE
Add mixin's interface to interface list of child class

### ISSUE THREAD

**Issue by pgenfer** [pgenfer/mixinSharp#13]
**Remark**: Issue #11 was split into two parts for easier administration. This is the first part.

Say I have the following mixin
```C#
public class NameMixin: INamed
{
    public string Name { get; set; }
}
```
and ```INamed``` is defined as follows
```C#
public interface INamed
{
    string Name { get; set; } = string.Empty;
}
```
Furthermore, I have the following class
```C#
public class Person
{
    NameMixin _name = new NameMixin();
}
```
When I mix the ```NameMixin``` class into my type, I would like the option for the type to be further augmented by having the ```INamed``` interface automatically added to its interface list.   

Thanks to @aluanhaddad for the suggestion of this feature.

**Comment by aluanhaddad** [comment]
This looks great. I just noticed that my example code which was posted here had a mistake where I had the property initializer in the interface instead of the implementing mixin. I corrected the code in the original issue. Thanks again.
